config/routes.rb
Rails.application.routes.draw do

 

  get 'granular_measure/new'

  get 'granular_measure/create'

  get 'granular_measure/edit'

  get 'granular_measure/update'

  get 'granular_measure/destroy'

  get 'indicators' => 'indicators#index'

  get 'metrics' => 'metrics#index'

  get 'details' => 'details#index'

  get 'error_you_can_not_access_page' => 'static_pages#error_you_can_not_access_page'
  get 'error_role_empty_page' => 'static_pages#error_role_empty_page'
  get 'success_page' => 'static_pages#success_page'
  get "user_roles/update" => "user_roles#update"
  put "user_roles/update" => "user_roles#update"
  get "user_roles/update_state" => "user_roles#update_state"
  put "user_roles/update_state" => "user_roles#update_state"

  resources :sites

  resources :addresses
  
  resources :roles, shallow: true do
    resources :facilities do
        resources :measures, :facility_static_measures, :kpis  do
          collection { post :import }
        end
    end
  end

  devise_for :users, :controllers => { :registrations => "my_devise/registrations"}

  root to: 'static_pages#landing_page'
  

end

app/models/facility.rb
class Facility < ActiveRecord::Base
	# include Kpi
  include CalculateIndicators
  include AuxiliarKpiCalc
  # include Wisper

	belongs_to :role, class_name: 'Role', foreign_key: 'role_id'
	has_one :user, :through => :role
	has_many :facility_static_measures, class_name: 'FacilityStaticMeasure', foreign_key: 'facility_id', dependent: :destroy
  has_many :indicators, class_name: 'Indicators', foreign_key: 'facility_id', dependent: :destroy
  has_many :measures, class_name: 'Measure', foreign_key: 'facility_id', dependent: :destroy
	has_one :site
	belongs_to :address, class_name: 'Address', foreign_key: 'address_id', dependent: :destroy

	accepts_nested_attributes_for :address

  validates :name, presence: true
	# accepts_nested_attributes_for :facility_static_measure

    def kpi_query nome, facility, year
      unless !year || year == ""
        #se o ano tiver sido especificado no search
        indicators = Indicator.where("name = ? AND facility_id = ? AND extract(year from date) = ?", RankingFacilities::Application::KPI_NAMES[nome], facility.id, year.to_i.to_s).sort_by{|vn| vn[:date]}
      else
        #se não o ano não tiver sido especificado no search
        indicators = Indicator.where("name = ? AND facility_id = ?", RankingFacilities::Application::KPI_NAMES[nome], facility.id).sort_by{|vn| vn[:date]}
        year=indicators.first.date.year
      end
      array = []
      indicators.each do |i|
        if i.value.to_s != "Infinity"
          array << i.value 
        else
          array << 0
        end
      end
     
      {:values => array, :name => RankingFacilities::Application::KPI_NAMES[nome], :facility_name => facility.name ,
      :type => RankingFacilities::Application::KPI_UNITS[nome], :x => :tlc, :y => :ae, :year => year}
    end


    # verifica qual a facility com melhores resultados de um determinado KPI
    def best_facility_method nome, facilities, year
      best_average = {}
      facilities.each do |f|

        results = kpi_query(nome, f, year)
 
        average = AuxiliarKpiCalc.avg results[:values]
        
        unless best_average[:average]
          best_average = {:results => results, :average => average}
        else 
          if average and average < best_average[:average] and results[:values] != [] #se der NaN, entao da menor..
            best_average = {:results => results, :average => average}
          end
        end
      end
      
      best_average
    end

    def best_kpi_query(nome, year, facilities)
        year = AuxiliarKpiCalc.specify_year year
        my_facility_results=kpi_query(nome, self, year)
        facilities = facilities || Facility.all
        best_average = best_facility_method nome, facilities, year
        
        my_facility_results[:values] = AuxiliarKpiCalc.calc_quarter_average(my_facility_results[:values])
        best_average[:results][:values] = AuxiliarKpiCalc.calc_quarter_average(best_average[:results][:values])
        
       
      
        {:my_facility_results => my_facility_results, :best_facility_results => best_average[:results][:values]}
    end

    def costs_year
      year = Date.current.year
      hash = {:first => {:name => year-2, :values => [AuxiliarKpiCalc.avg(kpi_query(:cc_nfa, self, (year-2).to_s)[:values]).round(2), AuxiliarKpiCalc.avg(kpi_query(:sc_nfa, self, (year-2).to_s)[:values]).round(2), AuxiliarKpiCalc.avg(kpi_query(:oc_nfa, self, (year-2).to_s)[:values]).round(2) ]}}
      hash[:second]={:name => year-1, :values => [AuxiliarKpiCalc.avg(kpi_query(:cc_nfa, self, (year-1).to_s)[:values]).round(2), AuxiliarKpiCalc.avg(kpi_query(:sc_nfa, self, (year-1).to_s)[:values]).round(2), AuxiliarKpiCalc.avg(kpi_query(:oc_nfa, self, (year-1).to_s)[:values]).round(2) ]}
      hash[:third]={:name => year, :values => [AuxiliarKpiCalc.avg(kpi_query(:cc_nfa, self, year.to_s)[:values]).round(2), AuxiliarKpiCalc.avg(kpi_query(:sc_nfa, self, year.to_s)[:values]).round(2), AuxiliarKpiCalc.avg(kpi_query(:oc_nfa, self, year.to_s)[:values]).round(2) ]}
      hash[:categories] = ["Cleaning", "Space", "Occupancy"]
      hash[:graph_name] = 'Cost per NFA'
      hash
    end

    def calculate_indicators facility, created_at
      if facility.id == self.id
        CalculateIndicators.calculate_indicators(facility, created_at)
      end
    end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_filter :require_login, :authenticate
  before_action :set_facility, only: [:show, :edit, :update, :destroy]


  # GET /facilities
  # GET /facilities.json
  def index
    @facilities = Role.find(current_user.current_role).facilities
  end

  # GET /facilities/1
  # GET /facilities/1.json
  # def show
  # end

  # GET /facilities/new
  def new
    @facility = Facility.new
    @facility.build_address
    @role = Role.find(current_user.current_role)
  end

  # GET /facilities/1/edit
  def edit
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(facility_params)
    # service = Measure.new
    # service.subscribe(@facility, async: :true)

    # service.on(:import_finished) { |facility, date_created_at| CalculateIndicators.calculate_indicators(facility, date_created_at) }
    # service.on(:added_measure) { |facility, date_created_at| CalculateIndicators.calculate_indicators(facility, date_created_at) }

    # service.execute(:nothing, 0, 0)
    respond_to do |format|
      if @facility.save

        format.html { redirect_to edit_facility_path(@facility), notice: 'Facility was successfully created.' }
        format.json { render :edit, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to edit_facility_path(@facility), notice: 'Facility was successfully updated.' }
        format.json { render :edit, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to success_page_url, notice: 'Facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:name, :role_id, :user_id, 
        address_attributes: [:street, :city, :country, :zip_code])
        # facility_static_measure_attributes: [:name, :value, :start_date, :end_date, :user_id, :facility_id])
    end

    def authenticate
      if params['id']
        unless current_user.id == Facility.find(params['id'].to_i).user.id 
          authenticate_app
        end
      end
      if params['role_id'] && Role.find(params['role_id']).facilities.first
        unless current_user.id == Role.find(params['role_id']).facilities.first.user.id
              authenticate_app
        end
      end
    end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper

	def get_classes(params, facility_id)
		if params[:facility_id]==facility_id.to_s || (params[:controller]=="facilities" && params[:id]==facility_id.to_s)
			"active"
		else
			""
		end
	end
end

app/views/facilities/_form.html.erb
  <%= form_for([@role, @facility], html: {class: "ls-box ls-board-box"}) do |f| %>

    <% if @facility.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

        <ul>
        <% @facility.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <fieldset>
    <div class="form_fancy"><%= f.label "Facility Name" %><br />
            <%= f.text_field :name, :required => true, class: "form-control input-field" %></div>
    
    <div id="" class="form_fancy">
        <strong><%= "Address" %></strong>
        <input id="autocomplete" onfocus="geolocate()" type="text" class="form-control input-field"></input>
    </div>
    <%= f.fields_for :address do |a| %>
      <div class="form_fancy"><%= a.label :street %><br />
      <%= a.text_field :street, :required => true, class: "form-control input-field", id: "route" %></div>
      <div class="form_fancy"><%= a.label :city %><br />
      <%= a.select :city, RankingFacilities::Application::CITIES.inject([]){|acum, (key, value) | acum << value } , {} ,:required => true, class: "select big", id: "locality" %></div>
      <div class="form_fancy"><%= a.label :country %><br />
      <%= a.select :country, RankingFacilities::Application::COUNTRY.inject([]){|acum, (key, value) | acum << value } , {} ,:required => true, class: "select big", id: "country" %></div>
      <div class="form_fancy"><%= a.label :zip_code %><br />
      <%= a.text_field :zip_code, :required => true, class: "form-control input-field", id: "postal_code" %></div><br/>
    <% end %>
    
    <%= f.hidden_field :role_id, :value => current_user.current_role %>
    <%= f.hidden_field :user_id, :value => current_user %>
    
    <div class="update_user pull-right">
      <%= f.submit "Save", class: "ls-btn-lg ls-no-radius" %>
      <% if @action[:action] == 'edit' %>
        <td><%= link_to 'Delete', @facility, class: "ls-btn-lg ls-no-radius" , method: :delete, data: { confirm: 'Are you sure?'} %></td>
      <% end %>
    </div>
    </fieldset>
  <% end %>


<% if @action[:action] == 'edit'%>
<!--   <div class="ls-list ls-no-radius">
        <header class="ls-list-header">
          <div class="ls-list-title col-md-4">
            <a href="#" class="titulo-azul">Facility Static Metrics</a>
           
          </div>
          <div class="col-md-6 col-md-offset-2 ls-txt-right ">
            
            <%= link_to 'New Facility Static Metrics', new_facility_facility_static_measure_path(params[:id]), class: "ls-btn ls-no-radius" %>
            <%= link_to 'View List', facility_facility_static_measures_path(params[:id]), class: "ls-btn ls-no-radius" %>
          </div>
        </header>
  </div>   <br/> -->

  <% @facility_actual = {:facility => @facility} %>
  <%= render '/facility_static_measures/index', @facility_actual %>
<% end %>

app/views/facilities/edit.html.erb
<h1 class="ls-title-intro">
	<div class="row">
	  <div class="col-xs-6 col-md-4 tab-center ">
	  	<div class="col-xs-6 col-md-4 col-md-offset-4 bottom-border">
	  		<div class="bold-circle details"></div>
	  		<h5 class="bold tab-selected">DETAILS</h5>
	  	</div>
	  </div>
	  <a href='<%= facility_measures_path(@facility.id) %>'><div class="col-xs-6 col-md-4 tab-center">
	  	<h5 class="bold tab-not-selected">MEASUREMENTS</h5>
	  </div></a>
	  <a href='<%= facility_kpis_path(@facility.id) %>'><div  class="col-xs-6 col-md-4 tab-center">
	  	<h5 class="bold tab-not-selected">REPORTS</h5>
	  </div></a>
	</div>
</h1>
<% @action = {:action => 'edit'} %>


<%= render 'form', @action %>

app/views/facilities/index.html.erb
<% content_for :verticalbar do %>
  <%= render 'details/navbarVertical' %>  
<% end %>
<div class="form_facility col-md-12">
<h1>Listing facilities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sector</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facilities.each do |facility| %>
      <tr>
        <td><%= facility.name %></td>
        <td><%= link_to 'Show', facility %></td>
        <td><%= link_to 'Edit', edit_facility_path(facility) %></td>
        <td><%= link_to 'Destroy', facility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Facility', new_role_facility_path(current_user.current_role) %>
</div>

app/views/facilities/new.html.erb
<h1 class="ls-title-intro ls-ico-plus">New Facility </h1>
<% @action = {:action => 'new'} %>
<%= render 'form' %>

app/views/facilities/show.html.erb
<% content_for :verticalbar do %>
	<%= render 'details/navbarVertical' %>	
<% end %>
<div class="form_facility col-md-12">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @facility.name %>
</p>
</div>