config/routes.rb
Rails.application.routes.draw do

 

  get 'granular_measure/new'

  get 'granular_measure/create'

  get 'granular_measure/edit'

  get 'granular_measure/update'

  get 'granular_measure/destroy'

  get 'indicators' => 'indicators#index'

  get 'metrics' => 'metrics#index'

  get 'details' => 'details#index'

  get 'error_you_can_not_access_page' => 'static_pages#error_you_can_not_access_page'
  get 'error_role_empty_page' => 'static_pages#error_role_empty_page'
  get 'success_page' => 'static_pages#success_page'
  get "user_roles/update" => "user_roles#update"
  put "user_roles/update" => "user_roles#update"
  get "user_roles/update_state" => "user_roles#update_state"
  put "user_roles/update_state" => "user_roles#update_state"

  resources :sites

  resources :addresses
  
  resources :roles, shallow: true do
    resources :facilities do
        resources :measures, :facility_static_measures, :kpis  do
          collection { post :import }
        end
    end
  end

  devise_for :users, :controllers => { :registrations => "my_devise/registrations"}

  root to: 'static_pages#landing_page'
  

end

app/models/measure.rb
class Measure < ActiveRecord::Base
	include DefineGranularMeasure
	belongs_to :facility, class_name: 'Facility', foreign_key: 'facility_id'
	has_one :user, :through => :facility
	has_many :granular_measures, class_name: 'GranularMeasure', foreign_key: 'measure_id', dependent: :destroy

	validates :name, presence: true
	validates :value, presence: true
	validates :start_date, presence: true
	validates :end_date, presence: true

	def self.import(file, facility_id, current_user)
	  spreadsheet = open_spreadsheet(file)
	  header = spreadsheet.row(1)
	  (2..spreadsheet.last_row).each do |i|
	    row = Hash[[header, spreadsheet.row(i)].transpose]
		if !row["name"] or !RankingFacilities::Application::METRIC_NAMES.inject([]){|acum, (key, value) | acum << value }.include? row["name"]
			raise "You have a empty or not valid values on 'name' column: "
		elsif row["value"] and !row["value"].is_a? Float
			raise "You have a  not valid values on 'value' column: "
		elsif row["start_date"] and !row["start_date"].is_a? Date
			raise "You have a  not valid values on 'start_date' column."
		elsif row["end_date"] and !row["end_date"].is_a? Date
			raise "You have a not valid values on 'end_date' column."
		end
			
		unless !row["name"] or !row["value"] or !row["start_date"] or !row["end_date"] 
	    measure = find_by_id(row["id"]) || new
	    row["facility_id"]= facility_id
	    row["user_id"]= current_user
	    measure.attributes = row.to_hash.slice(*Measure.attribute_names())
	    measure.save!
	    DefineGranularMeasure.add_granular_measure(measure)
		end
	  end
	end

	def self.open_spreadsheet(file)
		if(file)
		  case File.extname(file.original_filename)
		  when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
		  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
		  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
		  else raise "Unknown file type: #{file.original_filename}"
		  end
		else raise "Please select a file to import."
		end
	end

end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController
  include DefineGranularMeasure
  before_filter :require_login, :authenticate
  before_action :set_measure, only: [:show, :edit, :update, :destroy]

  # GET /measures
  # GET /measures.json
  def index
    # @measures = Facility.find().measures.sort_by{|vn| vn[:date]}
    @facility = Facility.find(params[:facility_id])
    @q = Facility.find(params[:facility_id]).measures.search(params[:q])
    @measures = @q.result(distinct: true)
    @measure = Measure.new
  end

  # GET /measures/1
  # GET /measures/1.json
  def show
  end

  # GET /measures/new
  def new
    @measure = Measure.new
    @facility = Facility.find(params[:facility_id])
  end

  # GET /measures/1/edit
  def edit
  end

  # POST /measures
  # POST /measures.json
  def create
    @measure = Measure.new(measure_params)
    
    respond_to do |format|
      if @measure.save
        DefineGranularMeasure.add_granular_measure(@measure)
        format.html { redirect_to edit_measure_path(@measure), notice: 'Measure was successfully created.' }
        format.json { render :edit, status: :created, location: @measure }
      else
        format.html { render :new }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measures/1
  # PATCH/PUT /measures/1.json
  def update
    respond_to do |format|
      if @measure.update(measure_params)
        format.html { redirect_to edit_measure_path(@measure), notice: 'Measure was successfully updated.' }
        format.json { render :edit, status: :ok, location: @measure }
      else
        format.html { render :edit }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measures/1
  # DELETE /measures/1.json
  def destroy
    @facility_id = @measure.facility.id
    @measure.destroy
    respond_to do |format|
      format.html { redirect_to facility_measures_path(@facility_id), notice: 'Measure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
      ImporterJob.new.async.perform( params[:file], params[:facility_id].to_i, current_user.id )
      redirect_to facility_measures_url(params[:facility_id]), notice: "Importing Measures."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measure
      @measure = Measure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measure_params
      params.require(:measure).permit(:name, :value, :start_date, :end_date, :user_id, :facility_id) #, :unit)
    end

    def authenticate
      if params[:id]
        unless current_user.id == Measure.find(params[:id].to_i).user.id 
          authenticate_app
        end
      end
      if params[:facility_id] && Facility.find(params[:facility_id])
        unless current_user.id == Facility.find(params[:facility_id]).user.id
              authenticate_app
        end
      end
    end
end

app/helpers/measures_helper.rb
module MeasuresHelper
end

app/views/measures/_form.html.erb
<%= form_for([@facility, @measure], html: {class: "ls-box ls-board-box"})  do |f| %>
  <% if @measure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measure.errors.count, "error") %> prohibited this measure from being saved:</h2>

      <ul>
      <% @measure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<fieldset>
  <div class="form_fancy">
      <%= f.label "Name" %> <br>
      <%= f.select :name, RankingFacilities::Application::METRIC_NAMES.values.sort , {} ,:required => true, class: "select big" %>
  </div>
  <div class="form_fancy">
    <%= f.label :value %><br>
    <%= f.text_field :value, class: "input-field big" %>
  </div>
  <div class="row">
    <div class="form_fancy col-md-3">
      <%= f.label :start_date %><br>
      <%= f.bootstrap_date :start_date %>
    </div>
    <div class="form_fancy col-md-3">
      <%= f.label :end_date %><br>
      <%= f.bootstrap_date :end_date%>
    </div>
  </div>
  <% if @action[:action] == 'new' %>
  <%= f.hidden_field :facility_id, :value => params[:facility_id] %>
  <% end %>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="actions pull-right">
    <%= f.submit "Save", class: "ls-btn ls-no-radius pull-right"  %>
  </div>
  </fieldset>
  <% end %>

app/views/measures/_new_form.html.erb
<%= form_for [@facility, @measure] do |f| %>
  <% if @measure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measure.errors.count, "error") %> prohibited this measure from being saved:</h2>

      <ul>
      <% @measure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form_fancy">
      <%= f.label "Name" %> <br>
      <%= f.select :name, RankingFacilities::Application::METRIC_NAMES.values.sort , {} ,:required => true, class: "select big" %>
  </div>
  <div class="form_fancy">
    <%= f.label :value %><br>
    <%= f.text_field :value, class: "input-field big" %>
  </div>
  <div class="row">
    <div class="form_fancy col-md-3">
      <%= f.label :start_date %><br>
      <%= f.bootstrap_date :start_date %>
    </div>
    <div class="form_fancy col-md-3">
      <%= f.label :end_date %><br>
      <%= f.bootstrap_date :end_date%>
    </div>
  </div>

  <%= f.hidden_field :facility_id, :value => params[:facility_id] %>

  <div class="pull-right">
    <%= f.submit "Save", class: "ls-btn ls-no-radius pull-right"  %>
  </div>

<% end %>

app/views/measures/edit.html.erb
<h1 class="ls-title-intro ls-ico-pencil">Edit Metric</h1>

<% @action = {:action => 'edit'} %>
<%= render 'form', @action%>

app/views/measures/index.html.erb
<h1 class="ls-title-intro">
  <div class="row">
    <a href='<%= edit_facility_path(@facility.id) %>'><div class="col-xs-6 col-md-4 tab-center ">
      <h5 class="bold tab-not-selected">DETAILS</h5>
    </div></a>
    <a href=''><div class="col-xs-6 col-md-4 tab-center">
      <div class="col-xs-9 col-md-7 col-md-offset-2 bottom-border">
        <div class="bold-circle measures"></div>
        <h5 class="bold tab-selected">MEASUREMENTS</h5>
      </div>
    </div></a>
    <a href='<%= facility_kpis_path(@facility.id) %>'><div  class="col-xs-6 col-md-4 tab-center">
      <h5 class="bold tab-not-selected">REPORTS</h5>
    </div></a>
  </div>
</h1>
<!-- <h1 class="ls-title-intro ls-ico-bars"><%= @facility.name %> Metrics <%= link_to '', new_facility_measure_path(params[:facility_id]), class: "ls-ico-plus pull-right" %></h1> -->


<!--   <div class="row ls-box ls-board-box">
    <header class="ls-info-header">
        <h2 class="ls-title-3 ls-ico-cloud-upload">Import Metrics</h2>
    </header>
    <div class="import_explanation col-md-6">
      <p> A CSV or Excel file can be used to import Measures. </p>
      <p> The columns of the file should be in this order:</p>
      <p> <strong>name</strong> - String Type </p>
      <p> <strong>value</strong> - Float Type </p>
      <p> <strong>start_date</strong> - Date Type </p>
      <p> <strong>end_date</strong> - Date Type </p>
    </div>
    <div class="form_fancy col-md-3 pull-right">  
      <br/>
      <br/>
      <%= form_tag import_facility_measures_path(params[:facility_id]), multipart: true do %>

      <div class="form_fancy"><%= file_field_tag :file %></div>
      <div class="form_fancy"><%= submit_tag "Import" , class: "ls-btn ls-no-radius"%></div>
    <% end %>
    </div>

  </div>
 -->
  <%= search_form_for [@facility, @q]  do |f| %>
    <div class="row">
      <div class="col-xs-6 col-md-4 tab-center">
      <%= f.label :name_cont %>
      <%= f.search_field :name_cont, class: "input-field" %>
      </div>
      <div class="col-xs-6 col-md-4 tab-center">
      <%= f.label "From:  " %>
      <%= f.bootstrap_date :start_date_gteq %>
      </div>
      <div class="col-xs-6 col-md-4 tab-center">
      <%= f.label "Untill:  " %>
      <%= f.bootstrap_date :end_date_lteq %>
      </div>
    </div>
<!--     <%= f.submit "Search", class: "btn btn-default pull-right"  %> -->
  <% end %>


  <br/>
  
  <div class="row bottom-border">
    
      <%= link_to 'Add', new_facility_measure_path(params[:facility_id]), class: "ls-btn-primary btn-add-facility ls-no-radius ls-ico-plus pull-right white-color-font" %>

      <a title="Import Metrics" class=" pull-right" data-ls-module="popover" 
          data-content='<div class="row col-xs-29 col-md-18 ls-box ls-board-box">
                          <header class="ls-info-header">
                              <h2 class="ls-title-3 ls-ico-cloud-upload">Import Metrics</h2>
                          </header>
                          <div class="import_explanation">
                            <p> A CSV or Excel file can be used to import Measures. </p>
                            <br/>
                            <br/>
                            <p> The columns of the file should be in this order:</p>
                            <div class="pull-right">
                              <p> <strong>name</strong> - String Type </p>
                              <p> <strong>value</strong> - Float Type </p>
                              <p> <strong>start_date</strong> - Date Type </p>
                              <p> <strong>end_date</strong> - Date Type </p>
                              
                              <br/>
                            </div>
                        <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
                            <div class="row">
                              <%= form_tag import_facility_measures_path(params[:facility_id]), multipart: true do %>

                              <div class="form_fancy col-md-6"><%= file_field_tag :file %></div>
                              <div class="form_fancy col-md-3" style="margin-left: 50px;"><%= submit_tag "Import" , class: "ls-btn ls-no-radius"%></div>
                              <% end %>
                            </div>
                          </div>

                        </div>' data-placement="left"><h1 class="titulo-azul ls-btn ls-no-radius ls-ico-cloud-upload pull-right">Import</h1></a>
                   
  </div>                      
  
  <table class="ls-table table-top-border">
    <thead>
      <tr>
          <th></th>
        <!-- Retorna o nome das measures por ordem alfabética -->
        <% RankingFacilities::Application::METRIC_NAMES.values.sort.each do |measure_name| %>
          <th class="table-measures-head"><%= measure_name %></th>
        <% end %>
        
      </tr>
    </thead>

    <tbody>
      <!-- @measures.group_by{ |x| [x.start_date.month, x.start_date.year] }.sort retorna as measures por ano e mês de inicio, por ordem de satrt_date, como o exemplo abaixo       
      [[[1, 2015],
        [#<Measure id: 13, name: "Water Consumption", value: 361580.0, start_date: "2015-01-01", end_date: "2015-01-31", facility_id: 1, user_id: 1, created_at: "2015-04-23 19:16:23", updated_at: "2015-04-23 19:16:23">,
         #<Measure id: 61, name: "Total Space Cost", value: 23468.0, start_date: "2015-01-01", end_date: "2015-01-31", facility_id: 1, user_id: 1, created_at: "2015-04-23 19:16:33", updated_at: "2015-04-23 19:16:33">,
         #<Measure id: 25, name: "Total Cleaning Cost", value: 257895.6, start_date: "2015-01-01", end_date: "2015-01-31", facility_id: 1, user_id: 1, created_at: "2015-04-23 19:16:25", updated_at: "2015-04-23 19:16:25">,
         #<Measure id: 49, name: "Total Labour Costs", value: 899961.3, start_date: "2015-01-01", end_date: "2015-01-31", facility_id: 1, user_id: 1, created_at: "2015-04-23 19:16:30", updated_at: "2015-04-23 19:16:30">,
         #<Measure id: 73, name: "Total Occupancy Cost", value: 45732.0, start_date: "2015-01-01", end_date: "2015-01-31", facility_id: 1, user_id: 1, created_at: "2015-04-23 19:16:35", updated_at: "2015-04-23 19:16:35">,
         #<Measure id: 37, name: "Actual Expenses", value: 1156559.0, start_date: "2015-01-01", end_date: "2015-01-31", facility_id: 1, user_id: 1, created_at: "2015-04-23 19:16:28", updated_at: "2015-04-23 19:16:28">,
         #<Measure id: 1, name: "Energy Consumption", value: 5287.0, start_date: "2015-01-01", end_date: "2015-01-31", facility_id: 1, user_id: 1, created_at: "2015-04-23 19:16:20", updated_at: "2015-04-23 19:16:20">]],
       [[2, 2015], -->
      <% @measures.group_by{ |x| [x.start_date.year, x.start_date.month] }.sort.each do |measures_by_monthyear| %>
          <% i=0 %>
          <tr>
          <td class="date-celula"><%=  Date::MONTHNAMES[measures_by_monthyear.first.second] %><br/><small><%= measures_by_monthyear.first.first %></small></td>
            <% measures_by_monthyear.last.sort_by{ |m| m[:name]}.each do |measure_alphabetically| %>
            
              <% while (measure_alphabetically.name != RankingFacilities::Application::METRIC_NAMES.values.sort[i]) %>
                  <td class="measure-celula">
                    
                    <%= link_to 'Add Metric', new_facility_measure_path, class: "ls-btn ls-no-radius" %><br/><br/>
                    
                  </td>
                   <% i = i+1 %>
              <% end %>
                <td class="measure-celula">
                 
                  <a href="#" class="ls-btn ls-no-radius" data-ls-module="popover" title="Edit" 
                  data-content='<%= link_to 'Edit', edit_measure_path(measure_alphabetically), class: "ls-btn-primary ls-no-radius" %><%= link_to 'Destroy', measure_alphabetically, method: :delete, data: { confirm: 'Are you sure?' }, class: "ls-btn-primary ls-no-radius" %>' >
                  <%= measure_alphabetically.value %><br/><br/>
                  <small><%= Date.parse(measure_alphabetically.start_date.to_s).strftime("%m/%d")%>-<%= Date.parse(measure_alphabetically.end_date.to_s).strftime("%m/%d") %></small></a>
                </td>
                <% i = i+1 %>
            <% end %>
            <% if i==6 %>
            <td class="measure-celula">
                    
                    <%= link_to 'Add Metric', new_facility_measure_path, class: "ls-btn ls-no-radius" %><br/><br/>
                    
                  </td>
            <% end %>
        </tr>
      <% end %>

    </tbody>
  </table>

<!--   <div class="row ls-box ls-board-box">
    <header class="ls-info-header">
        <h2 class="ls-title-3 ls-ico-plus">Add New Metric</h2>
    </header>
    <%= render 'new_form' %>
  </div> -->
  <br>

app/views/measures/new.html.erb
<h1 class="ls-title-intro ls-ico-plus">New Metric</h1>

<% @action = {:action => 'new'} %>
<%= render 'form', @action%>

app/views/measures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @measure.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @measure.value %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @measure.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @measure.end_date %>
</p>