config/routes.rb
Rails.application.routes.draw do

 

  get 'granular_measure/new'

  get 'granular_measure/create'

  get 'granular_measure/edit'

  get 'granular_measure/update'

  get 'granular_measure/destroy'

  get 'indicators' => 'indicators#index'

  get 'metrics' => 'metrics#index'

  get 'details' => 'details#index'

  get 'error_you_can_not_access_page' => 'static_pages#error_you_can_not_access_page'
  get 'error_role_empty_page' => 'static_pages#error_role_empty_page'
  get 'success_page' => 'static_pages#success_page'
  get "user_roles/update" => "user_roles#update"
  put "user_roles/update" => "user_roles#update"
  get "user_roles/update_state" => "user_roles#update_state"
  put "user_roles/update_state" => "user_roles#update_state"

  resources :sites

  resources :addresses
  
  resources :roles, shallow: true do
    resources :facilities do
        resources :measures, :facility_static_measures, :kpis  do
          collection { post :import }
        end
    end
  end

  devise_for :users, :controllers => { :registrations => "my_devise/registrations"}

  root to: 'static_pages#landing_page'
  

end

app/views/layouts/NAOPRECISO_navbarVertical.html.erb
    
        <div class="marketing"> 
            <div class="row">
                <div class="col-md-6">
                    <ul class="nav nav-list bs-docs-sidenav" role="tablist">
                        <li class="dropdown">
                            <a class="dropdown-toggle vertical-title" data-toggle="dropdown" href="#myModal">
                                <% if current_user.current_role != 0 %>
                                    <%= current_user.roles.find(current_user.current_role).name + ": " +  current_user.roles.find(current_user.current_role).company_name %> 
                                <% else %>
                                    <%= "Role Not Selected" %>
                                <% end %> 
                            <span class="caret"></span></a>
                            <ul class="dropdown-menu dropdown " role="menu">
                                <% current_user.roles.each do |r| %>
                                       
                                       <li><%= link_to r.name + ": " + r.company_name, :controller => "/user_roles", :current_role => r.id, :action => 'update', :method => :put, :approved => true %></li>
                                <% end %>
                                <li class="divider"></li>
                                <li><%= link_to "Edit Roles", roles_path %></li>
                                <li class="divider"></li>
                                <li><%= link_to "Add Roles", new_role_path %></li>
                            </ul>
                        </li>   
                    </ul> 
                </div>
                <div class="col-md-6">

                        <%=  link_to image_tag((("icon_60846copy.png" if current_user.state == "details") || "icon_60846.png"), :class => "img-polaroid", :style => "width: 30%; height: 20%;" ), :controller => "/user_roles", :state => "details", :action => 'update_state', :method => :put, :approved => true %>
                       

                        <%=  link_to image_tag((("icon_30982copy.png" if current_user.state == "metrics") || "icon_30982.png"), :class => "img-polaroid", :style => "width: 30%; height: 30%;" ) , :controller => "/user_roles", :state => "metrics", :action => 'update_state', :method => :put, :approved => true %>

                        <%=  link_to  image_tag((("icon_31048copy.png" if current_user.state == "indicators") || "icon_31048.png"), :class => "img-polaroid", :style => "width: 30%; height: 20%;" ), :controller => "/user_roles", :state => "indicators", :action => 'update_state', :method => :put, :approved => true %>

                </div> 
            </div>
            <hr class="featurette-divider">     
            <ul class="nav nav-list bs-docs-sidenav">
                <% if current_user.current_role != 0 && current_user.roles.find(current_user.current_role).has_facilities? %> 
                    <% if current_user.state == "details" %>
                        <% current_user.roles.find(current_user.current_role).facilities.each do |f| %>         
                            <li><%= link_to f.name, edit_facility_path(f.id) %></li>
                        <% end %>
                    <%  end %>
                    
                    <% if current_user.state == "metrics" %>
                        <% current_user.roles.find(current_user.current_role).facilities.each do |f| %>           
                            <li><%= link_to f.name, facility_measures_path(f.id) %></li>
                        <% end %>
                    <%  end %>

                    <% if current_user.state == "indicators" %>
                        <% current_user.roles.find(current_user.current_role).facilities.each do |f| %>           
                            <li><%= link_to f.name, facility_kpis_path(f.id) %></li>
                        <% end %>
                    <%  end %>
                    
                    
                <% else %>
                    <%= "There are no Roles selected." %>
                <% end %>
                <hr class="featurette-divider"> 
                <% if current_user.current_role != 0 %>
                    <li><%= link_to "+ Add Facility", new_role_facility_path(current_user.current_role) %></li>
                <% else %>
                    <li><%= link_to "+ Add Facility", error_role_empty_page_path %></li>
                <% end %>
            </ul>

        </div>

app/views/layouts/_footer.html.erb
<div class="footer col-md-12">
	<footer> 
		<p>© 2014 Company, Inc. · <a class="btn-link" href="#">Privacy</a> · <a class="btn-link" href="#">Terms</a></p>
	</footer>
</div>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    	<div class="container-fluid">
    		<a class="navbar-brand" href="/">UpRanking</a>
    		<div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav pull-right" role="tablist">
        				<li class="dropdown">
            				<a class="dropdown-toggle" data-toggle="dropdown" href="#myModal">
            				    <%= current_user.full_name %><span class="caret"></span></a>
            				<ul class="dropdown-menu pull-right" role="menu">
            					<li><%= link_to "Edit User Account", edit_user_registration_path %></li>
            					<li class="divider"></li>
            					<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            				</ul>
        				</li>	
        			</ul>
    		</div>
    	</div>
    </div>
<% end %>

app/views/layouts/_navbarVertical.html.erb
    
        <div class="marketing"> 
            <div class="row">
                <div class="col-md-6">
                    <ul class="nav nav-list bs-docs-sidenav" role="tablist">
                        <li class="dropdown">
                            <a class="dropdown-toggle vertical-title" data-toggle="dropdown" href="#myModal">
                                <% if current_user.current_role != 0 %>
                                    <%= current_user.roles.find(current_user.current_role).name + ": " +  current_user.roles.find(current_user.current_role).company_name %> 
                                <% else %>
                                    <%= "Role Not Selected" %>
                                <% end %> 
                            <span class="caret"></span></a>
                            <ul class="dropdown-menu dropdown " role="menu">
                                <% current_user.roles.each do |r| %>
                                       
                                       <li><%= link_to r.name + ": " + r.company_name, :controller => "/user_roles", :current_role => r.id, :action => 'update', :method => :put, :approved => true %></li>
                                <% end %>
                                <li class="divider"></li>
                                <li><%= link_to "Edit Roles", roles_path %></li>
                                <li class="divider"></li>
                                <li><%= link_to "Add Roles", new_role_path %></li>
                            </ul>
                        </li>   
                    </ul> 
                </div>
                <div class="col-md-6">

                        <%=  link_to image_tag((("icon_60846copy.png" if current_user.state == "details") || "icon_60846.png"), :class => "img-polaroid", :style => "width: 30%; height: 20%;" ), :controller => "/user_roles", :state => "details", :action => 'update_state', :method => :put, :approved => true %>
                       

                        <%=  link_to image_tag((("icon_30982copy.png" if current_user.state == "metrics") || "icon_30982.png"), :class => "img-polaroid", :style => "width: 30%; height: 30%;" ) , :controller => "/user_roles", :state => "metrics", :action => 'update_state', :method => :put, :approved => true %>

                        <%=  link_to  image_tag((("icon_31048copy.png" if current_user.state == "indicators") || "icon_31048.png"), :class => "img-polaroid", :style => "width: 30%; height: 20%;" ), :controller => "/user_roles", :state => "indicators", :action => 'update_state', :method => :put, :approved => true %>

                </div> 
            </div>
            <hr class="featurette-divider">     
            <ul class="nav nav-list bs-docs-sidenav">
                <% if current_user.current_role != 0 && current_user.roles.find(current_user.current_role).has_facilities? %> 
                    <% if current_user.state == "details" %>
                        <% current_user.roles.find(current_user.current_role).facilities.each do |f| %>         
                            <li><%= link_to f.name, edit_facility_path(f.id) %></li>
                        <% end %>
                    <%  end %>
                    
                    <% if current_user.state == "metrics" %>
                        <% current_user.roles.find(current_user.current_role).facilities.each do |f| %>           
                            <li><%= link_to f.name, facility_measures_path(f.id) %></li>
                        <% end %>
                    <%  end %>

                    <% if current_user.state == "indicators" %>
                        <% current_user.roles.find(current_user.current_role).facilities.each do |f| %>           
                            <li><%= link_to f.name, facility_kpis_path(f.id) %></li>
                        <% end %>
                    <%  end %>
                    
                    
                <% else %>
                    <%= "There are no Roles selected." %>
                <% end %>
                <hr class="featurette-divider"> 
                <% if current_user.current_role != 0 %>
                    <li><%= link_to "+ Add Facility", new_role_facility_path(current_user.current_role) %></li>
                <% else %>
                    <li><%= link_to "+ Add Facility", static_pages_error_role_empty_page_path %></li>
                <% end %>
            </ul>

        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="ls-theme-light-green">
	<head >
	  <title>UpRanking</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  
		<meta charset="utf-8">
	    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
	    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
	    <meta name="description" content="Insira aqui a descrição da página.">

	    <style>
	      html, body, #map-canvas {
	        height: 100%;
	        margin: 0px;
	        padding: 0px
	      }
	    </style>

	    <link href="http://assets.locaweb.com.br/locastyle/3.7.2/stylesheets/locastyle.css" rel="stylesheet" type="text/css">
	    <link rel="icon" sizes="192x192" href="/locawebstyle/assets/images/ico-boilerplate.png">
	    <link rel="apple-touch-icon" href="/locawebstyle/assets/images/ico-boilerplate.png">
	    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
	  	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places"></script>
		<script>
		    // This example displays an address form, using the autocomplete feature
		    // of the Google Places API to help users fill in the information.

		    var placeSearch, autocomplete;
		    var componentForm = {
		        // street_number: 'short_name',
		        route: 'long_name',
		        locality: 'long_name',
		        // administrative_area_level_1: 'short_name',
		        country: 'long_name',
		        postal_code: 'short_name'
		    };

		    function initialize() {
		        // Create the autocomplete object, restricting the search
		        // to geographical location types.
		        autocomplete = new google.maps.places.Autocomplete(
		            /** @type {HTMLInputElement} */(document.getElementById('autocomplete')),
		            { types: ['geocode'] });
		       
		        // When the user selects an address from the dropdown,
		        // populate the address fields in the form.
		        google.maps.event.addListener(autocomplete, 'place_changed', function () {
		            fillInAddress();
		        });
		    }
		    // [START region_fillform]
		    function fillInAddress() {
		        // Get the place details from the autocomplete object.
		        var place = autocomplete.getPlace();

		        for (var component in componentForm) {
		            document.getElementById(component).value = '';
		            document.getElementById(component).disabled = false;
		        }

		        // Get each component of the address from the place details
		        // and fill the corresponding field on the form.
		        for (var i = 0; i < place.address_components.length; i++) {
		            var addressType = place.address_components[i].types[0];
		            if (componentForm[addressType]) {
		                var val = place.address_components[i][componentForm[addressType]];
		                document.getElementById(addressType).value = val;

		            }
		        }
		    }
		    // [END region_fillform]

		    // [START region_geolocation]
		    // Bias the autocomplete object to the user's geographical location,
		    // as supplied by the browser's 'navigator.geolocation' object.
		    function geolocate() {
		        if (navigator.geolocation) {
		            navigator.geolocation.getCurrentPosition(function (position) {
		                var geolocation = new google.maps.LatLng(
		                    position.coords.latitude, position.coords.longitude);
		                var circle = new google.maps.Circle({
		                    center: geolocation,
		                    radius: position.coords.accuracy
		                });
		                autocomplete.setBounds(circle.getBounds());
		            });
		        }
		    }

		</script>
	  </head>
  <body onload="initialize() ">
  	<% if user_signed_in? %>
    <div class="ls-topbar">

      <!-- Notification bar -->
      <div class="ls-notification-topbar">
        <!-- Nome da Role Actual -->
<!--         <div class="ls-alerts-list">
          <% if current_user.current_role != 0 %>
               
	          	<%= link_to edit_role_path(current_user.current_role)  do %>
	          		<%= current_user.roles.find(current_user.current_role).company_name %><br/>
                	<small class="pull-right"><%= current_user.roles.find(current_user.current_role).name %></small> 
	          	<% end %>
          <% else %>
                <%= "Select a Role " %>
          <% end %>
        </div> -->

        <!-- User details -->
        <div class="ls-user-account">
<!--           <a href="#" class="ls-ico-user">
            <%= current_user.full_name %>
          </a>
          <nav class="ls-dropdown-nav ls-user-menu">
            <ul>
              <li><%= link_to "Edit User Account", edit_user_registration_path %></li>
              
            </ul>
          </nav> -->
          <h2 class="white-color-font"><%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: "white-color-font" %></h2>
        </div>
      </div>

      <!-- <span class="ls-show-sidebar ls-ico-menu"></span> -->

      <!-- Nome do produto/marca -->
      <h1 class="ls-brand-name"><a class="ls-ico-chart-bar-up" href="/">UpRanking</a></h1>
    </div>

    <!-- Container da pagina principal: yield -->
    <main class="ls-main ">
    	<% flash.each do |type, message| %>
	            <div class="alerts alert <%= flash_class type %>">
	              <button class="close" data-dismiss="alert">X</button>
	              <%= message %>
	            </div>
	    <% end %>
    	<div class="container-fluid" >    	
      		<%= yield %>
     	</div>
    </main>

    <!-- Barra Lateral Esquerda -->
    <aside class="ls-sidebar">

      <div class="ls-sidebar-inner">
<!--       	<div class="ls-title-intro sidebar-intro">
      		<div class="row">
      			<div class="col-xs-8 col-md-6 tab-center ">
				  	<h5 class="bold bottom-border">PROFILE</h5>
				</div>
				<a href=''><div  class="col-xs-8 col-md-6 tab-center">
			  		<h5>RANKING</h5>
			  	</div></a>
      		</div>
      	</div> -->
      	<h1 class="ls-title-intro side-bar-title">
      		<div class="col-xs-12 col-md-8 tab-center">
			  	<div class="col-xs-8 col-md-6 col-md-offset-6 bottom-border profile ">
			  		<div class="bold-circle profile"></div>
			  		<h5 class="bold profile">PROFILE</h5>
			  	</div>
	  		</div>
      	</h1>
      	<a href="<%= edit_user_registration_path %>"><div class="ls-brand-name secundario side-bar-user-name <%= get_classes_users(params) %> ">

      		<div class="circle-user user-image col-md-offset-3">
      			<div class="bold-circle user-details"></div>
      		</div>
      		<h4 class="">
      		<%= current_user.full_name %><br/><br/>
      		<p>	
 	      		<% if current_user.current_role != 0 %>
		          		<%= current_user.roles.find(current_user.current_role).company_name %><br/>
	                	<small><%= current_user.roles.find(current_user.current_role).name %></small>
	          	<% else %>
	                <%= "Select a Role " %>
	          	<% end %>
      		</p></h4>
      	
      	</div></a>
      	
      	
	    <nav class="ls-menu">
	      <ul>
	        
	          <!-- <a href="#" class="ls-ico-list3">Details</a> -->
	          <ul >
	            	<% if current_user.current_role != 0 && current_user.roles.find(current_user.current_role).has_facilities? %> 
	                    
	                        <% current_user.roles.find(current_user.current_role).facilities.each do |f| %>

	                            <%= link_to f.name, edit_facility_path(f.id), {class: get_classes(params, f.id)} %>
	                        <% end %> 
	                <% else %>
	                    <li><a class="ls-submenu" href="#">No Facilities</a></li>
	                <% end %>
	          </ul>
	       
	        <!-- <li class="ls-submenu">
	          <a href="#" class="ls-ico-bars">Metrics</a>
	          <ul role="menu">
	            	<% if current_user.current_role != 0 && current_user.roles.find(current_user.current_role).has_facilities? %> 
	                    
	                        <% current_user.roles.find(current_user.current_role).facilities.each do |f| %>         
	                            <%= link_to f.name, facility_measures_path(f.id) %>
	                        <% end %> 
	                <% else %>
	                    <li><a class="ls-submenu-item" href="#">No Facilities</a></li>
	                <% end %>
	          </ul>
	        </li>
	        <li class="ls-submenu">
	          <a href="#" class="ls-ico-dashboard">Reports</a>
	          <ul role="menu">
		          	<% if current_user.current_role != 0 && current_user.roles.find(current_user.current_role).has_facilities? %> 
	                    
	                        <% current_user.roles.find(current_user.current_role).facilities.each do |f| %>         
	                            <%= link_to f.name, facility_kpis_path(f.id), class: "ls-submenu-item" %>
	                        <% end %> 
	                <% else %>
	                    <li><a class="ls-submenu-item" href="#">No Facilities</a></li>
	                <% end %>
	          </ul>
	        </li> -->

	        <% if current_user.current_role != 0 %>
                <li><%= link_to "Add Facility", new_role_facility_path(current_user.current_role), class: "ls-ico-plus" %></li>
            <% end %>
	      </ul>

	    </nav>
	  </div>
    </aside>

    <% else %>
			   
			<%= yield %>

	<% end %>

    <script src="http://assets.locaweb.com.br/locastyle/3.7.2/javascripts/locastyle.js" type="text/javascript"></script>
</html>

app/views/layouts/applicationANTIGO.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>UpRanking</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <link rel="stylesheet" type="text/css" href="//assets.locaweb.com.br/locastyle/3.6.2/stylesheets/locastyle.css">
	</head>
	<!-- <body data-spy="scroll" data-target=".bs-docs-sidebar" data-twttr-rendered="true">

		<div class="row">
			<% if user_signed_in? %>
				<%= render 'layouts/navbar' %>	
				<div class="container-fluid">
					<div class="row-fluid">
						<div class="col-md-3 verticalbar affix">
					    	<%= yield :verticalbar %>	
					    </div>
					    <div class="container-conteudo col-md-9 col-md-offset-3">
					    	<% flash.each do |type, message| %>
					    		<div class="alert <%= flash_class type %>">
							    	<button class="close" data-dismiss="alert" >X</button>
							    	<%= message %>
							    </div>
					    	<% end %>

					        <%= yield %>

					        <%= render 'layouts/footer' %>
					    </div>


				    </div>
				</div>
			 <% else %>
			   		
			   	<div class="container col-md-12">
				   	<% flash.each do |type, message| %>
					    <div class="alert <%= flash_class type %>">
							<button class="close" data-dismiss="alert">X</button>
							<%= message %>
						</div>
					<% end %>
				    <%= yield %>
			    </div>
			<% end %>
			
		</div>
	</body> -->


	<body>
		<!-- Navbar Superior -->
<!-- 		<header class="navbar">
			<div class="container-fluid expanded-panel">
				<div class="row">
					<div id="logo" class="col-xs-12 col-sm-2">
						<a href="">UpRanking</a>
					</div>
					<div id="top-panel" class="col-xs-12 col-sm-10">
						<div class="row">
						
							<div class="col-xs-4 col-sm-8 top-panel-right pull-right">
								
								<ul class="nav navbar-nav pull-right panel-menu">
									<li class="dropdown">
										<a href="#" class="dropdown-toggle account" data-toggle="dropdown">
											<i class="fa fa-angle-down pull-right"></i>
											<div class="user-mini pull-right">
												<span class="welcome">Welcome,</span>
												<span><%= current_user.full_name %></span>
											</div>
										</a>
										<ul class="dropdown-menu">
			            					<li><%= link_to "Edit User Account", edit_user_registration_path %></li>
			            					<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
			            				</ul>
					
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header> -->
		<span class="ls-show-sidebar ls-ico-menu"></span>
		<aside class="ls-sidebar">
			<div data-ls-module="dropdown" class="ls-dropdown ls-user-account ls-active">
			  <a href="#" class="ls-ico-user">
			    <span class="ls-name">João</span>
			    (fmolina)</small>
			  </a>
			  <nav class="ls-dropdown-nav ls-user-menu">
			    <ul>
			      <li><a href="#">Meus dados</a></li>
			      <li><a href="#">Faturas</a></li>
			      <li><a href="#">Planos</a></li>
			     </ul>
			     <a href="#" class="ls-btn-logout">Sair</a>
			  </nav>
			</div>

			<div class="ls-sidebar-inner">
			    <a href="/locawebstyle/documentacao/exemplos/painel1/pre-painel"  class="ls-go-prev"><span class="ls-text">Voltar à lista de serviços</span></a>

			    <nav class="ls-menu">
			      <ul>
			         <li><a href="/locawebstyle/documentacao/exemplos/painel1/home" class="ls-ico-dashboard">Dashboard</a></li>
			         <li><a href="/locawebstyle/documentacao/exemplos/painel1/clients" class="ls-ico-users">Clientes</a></li>
			         <li><a href="/locawebstyle/documentacao/exemplos/painel1/stats" class="ls-ico-stats">Relatórios da revenda</a></li>
			         <li>
			          <a href="#" class="ls-ico-cog">Configurações</a>
			          <ul>
			            <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-domain">Domínios da Revenda</a></li>
			            <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-email">E-mail de Remetente</a></li>
			            <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-aspect">Aparência</a></li>
			            <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-answer">Atendimento</a></li>
			            <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-api">Chave de acesso para API</a></li>
			          </ul>
			        </li>
			      </ul>
			    </nav>

			</div>
		</aside>
		<!-- Container: tudo menos navbar -->
		<!-- <div id="main" class="container-fluid" role="navigation">
			<div class="row"> -->
				<!-- Side Bar Left -->
				<!-- <div id="sidebar-left" class="col-xs-2 col-sm-2">
					<ul class="nav main-menu"> -->

						<!-- Nome da Role Actual -->
						<!-- <li>
							<a href="ajax/dashboard.html" class="active ajax-link">
								<i class="fa fa-dashboard"></i>
								<span class="hidden-xs"><% if current_user.current_role != 0 %>
                                    <%= current_user.roles.find(current_user.current_role).name + ": " +  current_user.roles.find(current_user.current_role).company_name %> 
                                <% else %>
                                    <%= "Role Not Selected" %>
                                <% end %></span>
							</a>
						</li>
 -->
						<!-- Dropdown Lista Facilities: Details -->
						<!-- <li class="dropdown">
							<a href="#" class="dropdown-toggle">
								<i class="fa fa-bar-chart-o"></i>
								<span class="hidden-xs">Facility Details</span>
							</a>
							<ul class="dropdown-menu">
								<li><a class="ajax-link" href="ajax/charts_xcharts.html">xCharts</a></li>
								<li><a class="ajax-link" href="ajax/charts_flot.html">Flot Charts</a></li>
								<li><a class="ajax-link" href="ajax/charts_google.html">Google Charts</a></li>
								<li><a class="ajax-link" href="ajax/charts_morris.html">Morris Charts</a></li>
								<li><a class="ajax-link" href="ajax/charts_amcharts.html">AmCharts</a></li>
								<li><a class="ajax-link" href="ajax/charts_chartist.html">Chartist</a></li>
								<li><a class="ajax-link" href="ajax/charts_coindesk.html">CoinDesk realtime</a></li>
							</ul>
						</li> -->

						<!-- Dropdown Lista Facilities: Metricas -->
						<!-- <li class="dropdown">
							<a href="#" class="dropdown-toggle">
								<i class="fa fa-table"></i>
								 <span class="hidden-xs">Facility Metrics</span>
							</a>
							<ul class="dropdown-menu">
								<li><a class="ajax-link" href="ajax/tables_simple.html">Simple Tables</a></li>
								<li><a class="ajax-link" href="ajax/tables_datatables.html">Data Tables</a></li>
								<li><a class="ajax-link" href="ajax/tables_beauty.html">Beauty Tables</a></li>
							</ul>
						</li> -->

						<!-- Dropdown Lista Facilities: Reports -->
						<!-- <li class="dropdown">
							<a href="#" class="dropdown-toggle">
								<i class="fa fa-pencil-square-o"></i>
								 <span class="hidden-xs">Facility Reports</span>
							</a>
							<ul class="dropdown-menu">
								<li><a class="ajax-link" href="ajax/forms_elements.html">Elements</a></li>
								<li><a class="ajax-link" href="ajax/forms_layouts.html">Layouts</a></li>
								<li><a class="ajax-link" href="ajax/forms_file_uploader.html">File Uploader</a></li>
							</ul>
						</li>
						<span class="ls-sidebar-toggle ls-ico-shaft-left"></span> -->
						<!-- <li class="dropdown">
							<a href="#" class="dropdown-toggle">
								<i class="fa fa-picture-o"></i>
								 <span class="hidden-xs">Multilevel menu</span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="#">First level menu</a></li>
								<li><a href="#">First level menu</a></li>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle">
										<i class="fa fa-plus-square"></i>
										<span class="hidden-xs">Second level menu group</span>
									</a>
									<ul class="dropdown-menu">
										<li><a href="#">Second level menu</a></li>
										<li><a href="#">Second level menu</a></li>
										<li class="dropdown">
											<a href="#" class="dropdown-toggle">
												<i class="fa fa-plus-square"></i>
												<span class="hidden-xs">Three level menu group</span>
											</a>
										</li>
									</ul>
								</li>
							</ul>
						</li> -->
				<!-- 	</ul>
				</div> -->






<!-- 			</div>
		</div> -->




	</body>
</html>